intants_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('website.urls', 'website'), namespace='website')),
    path('', include('django_prometheus.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('download/', views.get_file, name='download'),
    path('download2/', views.get_file2, name='download2'),
    path('download3/', views.get_file3, name='download3'),
    path('download4/', views.get_file4, name='download4'),
    path('portfolio1/', views.portfolio1, name='portfolio1'),
    path('portfolio2/', views.portfolio2, name='portfolio2'),
    path('portfolio3/', views.portfolio3, name='portfolio3'),
    path('portfolio4/', views.portfolio4, name='portfolio4'),
    path('portfolio5/', views.portfolio5, name='portfolio5'),
    path('portfolio6/', views.portfolio6, name='portfolio6'),
    path('portfolio7/', views.portfolio7, name='portfolio7'),
    path('portfolio8/', views.portfolio8, name='portfolio8'),
    path('portfolio9/', views.portfolio9, name='portfolio9'),
]

website/models.py
from django.db import models

# Create your models here.

website/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(
        max_length=20,
        widget=forms.TextInput(
            attrs={'placeholder': 'Ваше имя', 'class': 'form-control'}
        )
    )

    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'placeholder': 'E-mail', 'class': 'form-control', 'type':'email'}
        )
    )
    
    number = forms.CharField(
        widget=forms.EmailInput(
            attrs={'placeholder': 'Номер телефона', 'class': 'form-control', 'type':'char'}
        )
    )

    subject = forms.CharField(
        max_length=20,
        widget=forms.TextInput(
            attrs={'placeholder': 'Тема сообщения', 'class': 'form-control', 'rows': 9}
        )
    )

    message = forms.CharField(
        max_length=200,
        widget=forms.Textarea(
            attrs={'placeholder': 'Сообщение', 'class': 'form-control', 'rows': 6}
        )
    )
    

website/views.py
from django.shortcuts import render
from django.http import FileResponse
from .forms import *
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.contrib.sessions.models import Session
from django.utils import timezone



# Create your views here.
def index(request):
    context = {}
    
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            # send_message(form.cleaned_data['name'], form.cleaned_data['email'], form.cleaned_data['subject'], form.cleaned_data['message'] )
            # context = {'success':1}
            list_answ = {}
            name = request.POST['name']
            email = request.POST['email']
            number = request.POST['number']
            subject = request.POST['subject']
            message = request.POST['message']
            with open("./media/request.txt", "a") as file:
                file.write('\n')
                file.write('--------------'+ '\n')
                file.write('Имя: ' + name + 'Е-mail: ' + email + '\n' + number + '\n')
                file.write('Тема письма: '+ '\n' + subject)
                file.write('Текст письма: ' + '\n' + message)

            return redirect(request.path)
        else:
            context = {'not_success':1}
    else:
        form = ContactForm()
    context['form'] = form
    return render(request, 'index.html', context=context)


def portfolio1(request):
    return render(request, 'portfolio-details_tsu.html')


def portfolio2(request):
    return render(request, 'portfolio-details_tpu.html')


def portfolio3(request):
    return render(request, 'portfolio-details_lk.html')


def portfolio4(request):
    return render(request, 'portfolio-details_tusur.html')


def portfolio5(request):
    return render(request, 'portfolio-details_ato.html')


def portfolio6(request):
    return render(request, 'portfolio-details_tnk.html')


def portfolio7(request):
    return render(request, 'portfolio-details_kkm.html')


def portfolio8(request):
    return render(request, 'portfolio-details_tvt.html')


def portfolio9(request):
    return render(request, 'portfolio-details_rnf.html')


def get_file(request):
    response = FileResponse(open('/app/media/Руководство_пользователя.pdf', 'rb'))
    return response

def get_file2(request):
    response = FileResponse(open('/app/media/Описание_продукта.pdf', 'rb'))
    return response

def get_file3(request):
    response = FileResponse(open('/app/media/Руководство_администратора.pdf', 'rb'))
    return response

def get_file4(request):
    response = FileResponse(open('/app/media/Пошаговая_инструкция_установки_ПО.pdf', 'rb'))
    return response

website/templates/Error.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Error</title>
</head>
<body>
    <hgroup>
        <h1>Error.</h1>
        <h2>An error occurred while processing your request.</h2>
    </hgroup>
</body>
</html>

website/templates/portfolio-details_ato.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Intans интегратор</title>
  <meta content="" name="description">

  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/logo.png' %}" rel="icon">
  <link href="{% static  'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static  'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static  'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static  'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static  'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static  'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static  'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="{% url 'website:index' %}" class="logo d-flex align-items-center">
        <img src="{% static  'assets/img/logo.png' %}" alt="">
        <span>Интант-Сервис</span>
      </a>

    </div>
  </header><!-- End Header -->

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <ol>
          <li><a type="button" onclick="history.back();">На главную</a></li>
          <li>Детали портфолио</li>
        </ol>
        <h2>Детали портфолио</h2>

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= Portfolio Details Section ======= -->
    <section id="portfolio-details" class="portfolio-details">
      <div class="container">

        <div class="row gy-4">

          <div class="col-lg-8">
            <div class="portfolio-details-slider swiper">
              <div class="swiper-wrapper align-items-center">

                <div class="swiper-slide">
                  <img src="{% static  'assets/img/portfolio/portfolio-5.jpg' %}" alt="">
                </div>

              </div>
              <div class="swiper-pagination"></div>
            </div>
          </div>

          <div class="col-lg-4">
            <div class="portfolio-info">
              <h3>Информация по проекту</h3>
              <ul>
                <li><strong>Категория</strong>: ИНФОРМАЦИОННАЯ БЕЗОПАСНОСТЬ
                </li>
                <li><strong>Заказчик</strong>: Администрация Томской области</li>
                <li><strong>Дата выполнения проекта</strong>: 01 March, 2021</li>
              </ul>
            </div>
            <div class="portfolio-description">
              <h2>Описание</h2>
              <p>
                В рамках выполнения государственного контракта специалистами группы компаний 'Интант' завершены комплексные работы по созданию мультисервисной сети и системы информационной безопасности органов государственной власти Томской области и местного самоуправления. В ходе реализация проекта была разработана стратегия развития мультисервисной сети передачи данных, которая обеспечивает модернизацию существующих и построение новых сетей связи, с учетом требований предъявляемых к современным технологиям передачи конфиденциальной информации и персональных данных по защищенным каналам связи.
              </p>
              <p>В области защиты данных, обрабатываемых и передаваемых в информационных системах органов государственной власти, и выполнения требований, регламентируемых действующим законодательством, в органах государственной власти был проведен аудит информационных систем персональных данных (ИСПДн). На основе проведенного аудита для каждого объекта был сформирован базовый пакет документации, который позволяет определить существующий уровень соответствия систем обработки персональных данных (ПДн) требованиям руководящих документов ФСБ, ФСТЭК и Роскомнадзора в области защиты персональных данных в автоматизированных системах обработки ПДн, а так же разработан пакет рекомендаций по приведению ИСПДн в соответствие требованиям ФЗ 152 «О персональных данных» и иным сопутствующим документам.</p>
            </div>
          </div>

        </div>

      </div>
    </section><!-- End Portfolio Details Section -->

  </main><!-- End #main -->

    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">

      <!-- <div class="footer-newsletter">
        <div class="container">
          <div class="row justify-content-center">
            
              <h4>Our Newsletter</h4>
              <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
            
            <div class="col-lg-6">
              <form action="" method="post">
                <input type="email" name="email"><input type="submit" value="Subscribe">
              </form>
            </div>
          </div>
        </div>
      </div> -->
  
      <div class="footer-top">
        <div class="container">
          <div class="row gy-4">
            <div class="col-lg-5 col-md-12 footer-info">
              <a href="index.html" class="logo d-flex align-items-center">
                <span>ООО "ИНТАНТ-Сервис"</span>
              </a>
              <p>Cистемный интегратор, 20 летний опыт проектирования и реализация IT-проектов различного уровня сложности.</p>
              <div class="social-links mt-3">
                <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
              </div>
            </div>
  
            <!-- <div class="col-lg-2 col-6 footer-links">
              <h4>Useful Links</h4>
              <ul>
                <li><i class="bi bi-chevron-right"></i> <a href="#">Home</a></li>
                <li><i class="bi bi-chevron-right"></i> <a href="#">About us</a></li>
                <li><i class="bi bi-chevron-right"></i> <a href="#">Services</a></li>
                <li><i class="bi bi-chevron-right"></i> <a href="#">Terms of service</a></li>
                <li><i class="bi bi-chevron-right"></i> <a href="#">Privacy policy</a></li>
              </ul>
            </div> -->
  
            <!-- <div class="col-lg-2 col-6 footer-links">
              <h4>Our Services</h4>
              <ul>
                <li><i class="bi bi-chevron-right"></i> <a href="#">Web Design</a></li>
                <li><i class="bi bi-chevron-right"></i> <a href="#">Web Development</a></li>
                <li><i class="bi bi-chevron-right"></i> <a href="#">Product Management</a></li>
                <li><i class="bi bi-chevron-right"></i> <a href="#">Marketing</a></li>
                <li><i class="bi bi-chevron-right"></i> <a href="#">Graphic Design</a></li>
              </ul>
            </div> -->
  
            <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
              <h4>Свяжитесь с нами</h4>
              <p>
          ООО "Интант-Сервис"
          г.Томск ул. Вершинина 43В <br>
                Россия <br><br>
                <strong>Телефон:</strong> (3822) 56-30-80 <br>
                <strong>Почта:</strong> info@intant.ru<br>
              </p>
  
            </div>
  
          </div>
        </div>
      </div>
  
      <div class="container">
        <div class="copyright">
          &copy; Copyright <strong><span>ООО "ИНТАНТ-Сервис"</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/flexstart-bootstrap-startup-template/ -->
          Designed by <a>Young Student</a>
        </div>
      </div>
    </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<script src="{% static  'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
<script src="{% static  'assets/vendor/aos/aos.js' %}"></script>
<script src="{% static  'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static  'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static  'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static  'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static  'assets/vendor/php-email-form/validate.js' %}"></script>


  <!-- Template Main JS File -->
  <script src="assets/js/main.js"></script>

</body>

</html>

website/templates/portfolio-details_kkm.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Intans интегратор</title>
  <meta content="" name="description">

  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/logo.png' %}" rel="icon">
  <link href="{% static  'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static  'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static  'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static  'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static  'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static  'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static  'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="{% url 'website:index' %}" class="logo d-flex align-items-center">
        <img src="{% static  'assets/img/logo.png' %}" alt="">
        <span>Интант-Сервис</span>
      </a>

    </div>
  </header><!-- End Header -->

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <ol>
          <li><a type="button" onclick="history.back();">На главную</a></li>
          <li>Детали портфолио</li>
        </ol>
        <h2>Детали портфолио</h2>

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= Portfolio Details Section ======= -->
    <section id="portfolio-details" class="portfolio-details">
      <div class="container">

        <div class="row gy-4">

          <div class="col-lg-8">
            <div class="portfolio-details-slider swiper">
              <div class="swiper-wrapper align-items-center">

                <div class="swiper-slide">
                  <img src="{% static  'assets/img/portfolio/portfolio-7.jpg' %}" alt="">
                </div>

              </div>
              <div class="swiper-pagination"></div>
            </div>
          </div>

          <div class="col-lg-4">
            <div class="portfolio-info">
              <h3>Информация по проекту</h3>
              <ul>
                <li><strong>Категория</strong>: Видео-конференц связь</li>
                <li><strong>Заказчик</strong>: Красноярский краевой медицинский информационно-аналитический центр</li>
                <li><strong>Дата выполнения проекта</strong>: 01 March, 2021</li>
              </ul>
            </div>
            <div class="portfolio-description">
              <h2>Описание</h2>
              <p>
                Группа компаний «Интант» создала систему видеоконференцсвязи для нужд Красноярского краевого медицинского информационно-аналитического центра. Решение ВКС строилось на базе оборудования Telepresence компании Cisco Systems. В основу предложенного решения вошли такие продукты:</p>
<p>1. Cервер сигнализации, используемый для управления вызовами, на базе программно-аппаратного комплекса Cisco VCS Control</p>
<p>2. Cервер управления системой ВКС на базе программно-аппаратного комплекса Cisco TMS</p>
<p>3. Мост видеоконференцсвязи для организации многоточечной связи на базе Cisco MCU 4200 и устройства конечных абонентов на основе программных клиентов Cisco Movi.</p>
<p>Система позволяет организовывать видеоконференции с общим количеством до 30 одновременных участников, предоставляет возможность подключения в ВКС по Web, возможность использовать видео высокого разрешения, формирует индивидуальные видео-потоки для каждого абонента в зависимости от его условий и требований с возможностью транскодирования в режиме реального времени. Реализованная сисетма является многофункциональной и масштабируемой, поддерживает возможность подключения в будущем конференц-комнат и систем комбинированного назначения без модернизации ядра системы.
              </p>
            </div>
          </div>

        </div>

      </div>
    </section><!-- End Portfolio Details Section -->

  </main><!-- End #main -->

    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">

      <!-- <div class="footer-newsletter">
        <div class="container">
          <div class="row justify-content-center">
            
              <h4>Our Newsletter</h4>
              <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
            
            <div class="col-lg-6">
              <form action="" method="post">
                <input type="email" name="email"><input type="submit" value="Subscribe">
              </form>
            </div>
          </div>
        </div>
      </div> -->
  
      <div class="footer-top">
        <div class="container">
          <div class="row gy-4">
            <div class="col-lg-5 col-md-12 footer-info">
              <a href="index.html" class="logo d-flex align-items-center">
                <span>ООО "ИНТАНТ-Сервис"</span>
              </a>
              <p>Cистемный интегратор, 20 летний опыт проектирования и реализация IT-проектов различного уровня сложности.</p>
              <div class="social-links mt-3">
                <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
              </div>
            </div>
  
            <!-- <div class="col-lg-2 col-6 footer-links">
              <h4>Useful Links</h4>
              <ul>
                <li><i class="bi bi-chevron-right"></i> <a href="#">Home</a></li>
                <li><i class="bi bi-chevron-right"></i> <a href="#">About us</a></li>
                <li><i class="bi bi-chevron-right"></i> <a href="#">Services</a></li>
                <li><i class="bi bi-chevron-right"></i> <a href="#">Terms of service</a></li>
                <li><i class="bi bi-chevron-right"></i> <a href="#">Privacy policy</a></li>
              </ul>
            </div> -->
  
            <!-- <div class="col-lg-2 col-6 footer-links">
              <h4>Our Services</h4>
              <ul>
                <li><i class="bi bi-chevron-right"></i> <a href="#">Web Design</a></li>
                <li><i class="bi bi-chevron-right"></i> <a href="#">Web Development</a></li>
                <li><i class="bi bi-chevron-right"></i> <a href="#">Product Management</a></li>
                <li><i class="bi bi-chevron-right"></i> <a href="#">Marketing</a></li>
                <li><i class="bi bi-chevron-right"></i> <a href="#">Graphic Design</a></li>
              </ul>
            </div> -->
  
            <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
              <h4>Свяжитесь с нами</h4>
              <p>
          ООО "Интант-Сервис"
          г.Томск ул. Вершинина 43В <br>
                Россия <br><br>
                <strong>Телефон:</strong> (3822) 56-30-80 <br>
                <strong>Почта:</strong> info@intant.ru<br>
              </p>
  
            </div>
  
          </div>
        </div>
      </div>
  
      <div class="container">
        <div class="copyright">
          &copy; Copyright <strong><span>ООО "ИНТАНТ-Сервис"</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/flexstart-bootstrap-startup-template/ -->
          Designed by <a>Young Student</a>
        </div>
      </div>
    </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<script src="{% static  'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
<script src="{% static  'assets/vendor/aos/aos.js' %}"></script>
<script src="{% static  'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static  'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static  'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static  'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static  'assets/vendor/php-email-form/validate.js' %}"></script>


  <!-- Template Main JS File -->
  <script src="assets/js/main.js"></script>

</body>

</html>